const MASTER_DATA_PAGE_CONFIG = {
	workLocations: {
		resource: 'work-locations',
		title: 'Master Work Location',
		breadcrumb: 'Work Location',
		groupBreadcrumb: 'Master Data Karyawan',
		fieldLabel: 'Work Location',
		fieldPlaceholder: 'Masukkan work location',
		description: 'Kelola daftar work location yang akan dipakai pada data karyawan.',
		fields: [
			{
				name: 'name',
				label: 'Work Location',
				placeholder: 'Masukkan work location',
				searchable: true,
			},
		],
		tableColumns: [
			{ id: 'id', label: 'NO' },
			{ id: 'name', label: 'WORK LOCATION' },
		],
	},
	departments: {
		resource: 'departments',
		title: 'Master Department',
		breadcrumb: 'Department',
		groupBreadcrumb: 'Master Data Karyawan',
		fieldLabel: 'Department',
		fieldPlaceholder: 'Masukkan department',
		description: 'Kelola daftar department untuk struktur organisasi karyawan.',
		fields: [
			{
				name: 'name',
				label: 'Department',
				placeholder: 'Masukkan department',
				searchable: true,
			},
		],
		tableColumns: [
			{ id: 'id', label: 'NO' },
			{ id: 'name', label: 'DEPARTMENT' },
		],
	},
	jobRoles: {
		resource: 'job-roles',
		title: 'Master Job Role',
		breadcrumb: 'Job Role',
		groupBreadcrumb: 'Master Data Karyawan',
		fieldLabel: 'Job Role',
		fieldPlaceholder: 'Masukkan job role',
		description: 'Kelola daftar job role atau peran kerja karyawan.',
		fields: [
			{
				name: 'name',
				label: 'Job Role',
				placeholder: 'Masukkan job role',
				searchable: true,
			},
		],
		tableColumns: [
			{ id: 'id', label: 'NO' },
			{ id: 'name', label: 'JOB ROLE' },
		],
	},
	jobLevels: {
		resource: 'job-levels',
		title: 'Master Job Level',
		breadcrumb: 'Job Level',
		groupBreadcrumb: 'Master Data Karyawan',
		fieldLabel: 'Job Level',
		fieldPlaceholder: 'Masukkan job level',
		description: 'Kelola daftar level jabatan karyawan.',
		fields: [
			{
				name: 'name',
				label: 'Job Level',
				placeholder: 'Masukkan job level',
				searchable: true,
			},
		],
		tableColumns: [
			{ id: 'id', label: 'NO' },
			{ id: 'name', label: 'JOB LEVEL' },
		],
	},
	masterUnits: {
		resource: 'master-units',
		title: 'Master Unit',
		breadcrumb: 'Master Unit',
		groupBreadcrumb: 'Master Data Unit',
		fieldLabel: 'Master Unit',
		fieldPlaceholder: 'Masukkan nama unit',
		description: 'Kelola daftar unit operasional beserta jenis, kapasitas, dan nomor unit.',
		searchPlaceholder: 'Nama unit, jenis unit, serial number...',
		itemNameField: 'unitName',
		fields: [
			{
				name: 'unitName',
				label: 'Nama Unit',
				placeholder: 'Masukkan nama unit',
				searchable: true,
			},
			{
				name: 'unitType',
				label: 'Jenis Unit',
				placeholder: 'Pilih jenis unit',
				type: 'select',
				options: ['Forklift', 'Cargo Lift', 'Kendaraan', 'Infrastruktur'],
				searchable: true,
			},
			{
				name: 'capacity',
				label: 'Kapasitas',
				placeholder: 'Masukkan kapasitas',
				searchable: true,
			},
			{
				name: 'unitSerialNumber',
				label: 'Unit/Serial Number',
				placeholder: 'Masukkan unit atau serial number',
				searchable: true,
			},
			{
				name: 'detailLainnya',
				label: 'Detail Lainnya',
				placeholder: 'Masukkan detail lainnya',
				searchable: true,
			},
		],
		tableColumns: [
			{ id: 'id', label: 'NO' },
			{ id: 'unitName', label: 'NAMA UNIT' },
			{ id: 'unitType', label: 'JENIS UNIT' },
			{ id: 'capacity', label: 'KAPASITAS' },
			{ id: 'unitSerialNumber', label: 'UNIT/SERIAL NUMBER' },
			{ id: 'detailLainnya', label: 'DETAIL LAINNYA' },
		],
		import: {
			title: 'Import Master Unit',
			description:
				'Unduh template Excel resmi, isi data unit operasional secara bulk, lalu upload file `.xlsx` untuk import.',
			templateHref: '/api/master/master-units/template',
		},
	},
	masterVendors: {
		resource: 'master-vendors',
		title: 'Master Vendor',
		breadcrumb: 'Master Vendor',
		groupBreadcrumb: 'Master Data Unit',
		fieldLabel: 'Master Vendor',
		fieldPlaceholder: 'Masukkan nama vendor',
		description: 'Kelola daftar vendor beserta jenis, kontak, dan informasi pendukung lainnya.',
		searchPlaceholder: 'Nama vendor, jenis vendor, PIC, email...',
		itemNameField: 'vendorName',
		fields: [
			{
				name: 'vendorName',
				label: 'Nama Vendor',
				placeholder: 'Masukkan nama vendor',
				searchable: true,
			},
			{
				name: 'vendorType',
				label: 'Jenis Vendor',
				placeholder: 'Pilih jenis vendor',
				type: 'select-custom',
				options: ['Consumable', 'Building', 'Trucking', 'Jasa', 'Warehousing', 'Disposable'],
				customOptionLabel: 'Lainnya',
				customPlaceholder: 'Masukkan jenis vendor lainnya',
				searchable: true,
			},
			{
				name: 'address',
				label: 'Alamat',
				placeholder: 'Masukkan alamat vendor',
				searchable: true,
			},
			{
				name: 'picName',
				label: 'Nama PIC',
				placeholder: 'Masukkan nama PIC',
				searchable: true,
			},
			{
				name: 'phoneNumber',
				label: 'Nomor Telfon',
				placeholder: 'Masukkan nomor telfon',
				searchable: true,
			},
			{
				name: 'email',
				label: 'Email',
				placeholder: 'Masukkan email',
				searchable: true,
			},
			{
				name: 'detailLainnya',
				label: 'Detail Lainnya',
				placeholder: 'Masukkan detail lainnya',
				searchable: true,
			},
		],
		tableColumns: [
			{ id: 'id', label: 'NO' },
			{ id: 'vendorName', label: 'NAMA VENDOR' },
			{ id: 'vendorType', label: 'JENIS VENDOR' },
			{ id: 'address', label: 'ALAMAT' },
			{ id: 'picName', label: 'NAMA PIC' },
			{ id: 'phoneNumber', label: 'NOMOR TELFON' },
			{ id: 'email', label: 'EMAIL' },
			{ id: 'detailLainnya', label: 'DETAIL LAINNYA' },
		],
	},
	masterDokPkb: {
		resource: 'master-dok-pkb',
		title: 'Master Dok PKB',
		breadcrumb: 'Master Dok PKB',
		groupBreadcrumb: 'Master Data Dokumen',
		fieldLabel: 'Master Dok PKB',
		fieldPlaceholder: 'Masukkan pasal PKB',
		description: 'Kelola master dokumen PKB berupa pasal dan isi dokumen.',
		searchPlaceholder: 'Pasal, isi, nomor...',
		fields: [
			{
				name: 'article',
				label: '(PKB) Pasal',
				placeholder: 'Masukkan pasal PKB',
				searchable: true,
			},
			{
				name: 'content',
				label: 'Isi',
				placeholder: 'Masukkan isi dokumen PKB',
				type: 'multiline',
				rows: 5,
				searchable: true,
			},
		],
		tableColumns: [
			{ id: 'id', label: 'NO' },
			{ id: 'article', label: '(PKB) PASAL' },
			{ id: 'content', label: 'ISI' },
		],
		import: {
			title: 'Import Master Dok PKB',
			description:
				'Unduh template Excel resmi, isi data pasal dan isi dokumen PKB secara bulk, lalu upload file `.xlsx` untuk import.',
			templateHref: '/templates/master-dok-pkb-import-template.xlsx',
		},
	},
	masterCutiKaryawan: {
		resource: 'master-cuti-karyawan',
		title: 'Master Cuti Karyawan',
		breadcrumb: 'Master Cuti Karyawan',
		groupBreadcrumb: 'Master Data Dokumen',
		fieldLabel: 'Master Cuti Karyawan',
		fieldPlaceholder: 'Masukkan jenis cuti',
		description: 'Kelola daftar jenis cuti karyawan yang dipakai pada modul pengajuan cuti.',
		searchPlaceholder: 'Jenis cuti, nomor...',
		itemNameField: 'leaveType',
		fields: [
			{
				name: 'leaveType',
				label: 'Jenis Cuti',
				placeholder: 'Masukkan jenis cuti',
				searchable: true,
			},
		],
		tableColumns: [
			{ id: 'id', label: 'NO' },
			{ id: 'leaveType', label: 'JENIS CUTI' },
		],
	},
};

export default MASTER_DATA_PAGE_CONFIG;
